blueprint:
  name: IKEA E1812 TRÅDFRI Shortcut Button (ZHA, firmware 24.x.x)
  description: >
    Automation for performing actions triggered by an IKEA E1812 TRÅDFRI
    Shortcut Button.
    Supports ZHA only, requires that the button is upgraded to firmware 24.x.x.



    This integration generates events compatible with Hooks from the
    [Awesome HA Blueprints](https://epmatt.github.io/awesome-ha-blueprints)
    project.



    Version: 0.1.1
  source_url: https://github.com/kepstin/ha-blueprints/blob/main/automation/ikea_e1812_zha.yaml
  domain: automation
  input:
    zha_controller_device:
      name: ZHA Controller Device (required)
      selector:
        device:
          integration: zha

    action_button_short:
      name: Button short press action
      default: []
      selector:
        action:

    action_button_double:
      name: Button double press action
      default: []
      selector:
        action:

    action_button_long:
      name: Button long press action
      default: []
      selector:
        action:

    action_button_release:
      name: Button long press release action
      default: []
      selector:
        action:

    button_long_loop:
      name: Button long press - loop until release
      default: false
      selector:
        boolean:

    button_long_max_loop_repeats:
      name: Button long press - maximum loop repeats
      default: 500
      selector:
        number:
          min: 1
          max: 5000
          mode: slider
          step: 1

mode: restart
max_exceeded: silent

variables:
  button_long_loop: !input button_long_loop
  button_long_max_loop_repeats: !input button_long_max_loop_repeats

trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input zha_controller_device

action:
  - choose:
      - conditions:
          - alias: Button short press
            condition: "{{ trigger.event.data.command == 'on' }}"
        sequence:
          - alias: Send awesome-ha-blueprints controller event
            event: ahb_controller_event
            event_data:
              controller: !input zha_controller_device
              action: button_short
          - alias: Run custom action
            choose:
              - conditions: []
                sequence: !input action_button_short

      - conditions:
          - alias: Button double press
            condition: "{{ trigger.event.data.command == 'off' }}"
        sequence:
          - alias: Send awesome-ha-blueprints controller event
            event: ahb_controller_event
            event_data:
              controller: !input zha_controller_device
              action: button_double
          - alias: Run custom action
            choose:
              - conditions: []
                sequence: !input action_button_double

      - conditions:
          - alias: Button long press
            condition: "{{ trigger.event.data.command == 'move_with_on_off' }}"
        sequence:
          - alias: Send awesome-ha-blueprints controller event
            event: ahb_controller_event
            event_data:
              controller: !input zha_controller_device
              action: button_long
          - alias: Run custom action with looping
            repeat:
              sequence: !input action_button_long
              until: "{{ not button_long_loop or repeat.index >= button_long_max_loop_repeats | int }}"

      - conditions:
          - alias: Button release
            condition: "{{ trigger.event.data.command == 'stop_with_on_off' }}"
        sequence:
          - event: ahb_controller_event
            event_data:
              controller: !input zha_controller_device
              action: button_release
          - choose:
              - conditions: []
                sequence: !input action_button_release
